org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft Properties
minecraft_version=1.21.7
minecraft_version_range=[1.21.7,)
forge_version=57.0.2
forge_version_range=[0,)
loader_version_range=[0,)
mapping_channel=official
mapping_version=1.21.7

# Mod Properties
mod_id=cratedelight
mod_name=Crate Delight
mod_license=MIT
mod_version=26.07.01-1.21.7-forge
mod_group_id=com.axperty.cratedelight
mod_authors=Axperty
mod_description=A mod that adds more crates and bags to the game.