org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
loader_version=0.16.8

# Mod Properties
mod_id=cratedelight
mod_name=Crate Delight
mod_license=MIT
mod_version=26.07.01-1.21.3-fabric
mod_authors=Axperty
mod_description=A mod that adds more crates and bags to the game.
maven_group=com.axperty
archives_base_name=cratedelight

# Dependencies
fabric_version=0.106.1+1.21.3