org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21
yarn_mappings=1.21+build.2
loader_version=0.15.11

fabric_version=0.100.3+1.21

# Mod Properties
modid = cratedelight
mod_version = 24.8.30-1.21-fabric
maven_group = com.axperty
archives_base_name = cratedelight
project_id=957811