modLoader="javafml"
loaderVersion="[62,)"
license="MIT License"

[[mods]]
modId="cratedelight"
version="26.03.26+26.1-forge"
displayName="Crate Delight"
authors="Axperty"
description='''A mod that adds more crates and bags to the game.'''
logoFile="assets/cratedelight/logo.png"

[[dependencies.cratedelight]]
modId="forge"
mandatory=true
versionRange="[62,)"
ordering="NONE"
side="BOTH"

[[dependencies.cratedelight]]
modId="minecraft"
mandatory=true
versionRange="[26.1,26.2,)"
ordering="NONE"
side="BOTH"