modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT License"

[[mods]]
modId="cratedelight"
version="25.09.22-1.21.7-forge"
displayName="Crate Delight"
authors="Axperty"
description='''A mod that adds crates and bags to the game.'''
logoFile="assets/cratedelight/logo.png"

[[dependencies.cratedelight]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.cratedelight]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
