modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL = "https://github.com/axperty/cratedelight/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL = "https://www.curseforge.com/members/axperty/projects"
logoFile="logo.png"
logoBlur = false
authors="${mod_authors}"
description="A mod that adds crates and bags to the game."

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"